import type { SourceEntry } from "../../types.ts";

export const sources: SourceEntry[] = [
  // Reddit sources
  {
    type: "reddit",
    id: "reddit-bangtan",
    label: "r/bangtan",
    url: "bangtan",
    needsFilter: false,
    fetchCount: 15,
    priority: 1,
  },
  {
    type: "reddit",
    id: "reddit-kpop",
    label: "r/kpop",
    url: "kpop",
    needsFilter: true,
    fetchCount: 15,
    priority: 2,
  },
  {
    type: "reddit",
    id: "reddit-heungtan",
    label: "r/heungtan",
    url: "heungtan",
    needsFilter: false,
    fetchCount: 15,
    priority: 3,
  },
  {
    type: "reddit",
    id: "reddit-bts7",
    label: "r/bts7",
    url: "bts7",
    needsFilter: false,
    fetchCount: 15,
    priority: 4,
  },

  // YouTube sources
  {
    type: "youtube",
    id: "yt-bangtantv",
    label: "BANGTANTV",
    url: "UCLkAepWjdylmXSltofFvsYQ",
    needsFilter: false,
    fetchCount: 10,
    priority: 5,
  },
  {
    type: "youtube",
    id: "yt-hybe",
    label: "HYBE LABELS",
    url: "UC3IZKseVpdzPSBaWxBxundA",
    needsFilter: true,
    fetchCount: 10,
    priority: 6,
  },

  // RSS sources
  {
    type: "rss",
    id: "rss-soompi",
    label: "Soompi",
    url: "https://www.soompi.com/feed",
    needsFilter: true,
    fetchCount: 10,
    priority: 7,
  },
  {
    type: "rss",
    id: "rss-allkpop",
    label: "AllKPop",
    url: "https://www.allkpop.com/feed",
    needsFilter: true,
    fetchCount: 10,
    priority: 8,
  },

  // Additional Reddit sources
  {
    type: "reddit",
    id: "reddit-kpoopheads",
    label: "r/kpoopheads",
    url: "kpoopheads",
    needsFilter: true,
    fetchCount: 10,
    priority: 10,
  },
  {
    type: "reddit",
    id: "reddit-btsworld",
    label: "r/BTSWorld",
    url: "BTSWorld",
    needsFilter: false,
    fetchCount: 10,
    priority: 11,
  },

  // Fan YouTube channels
  {
    type: "youtube",
    id: "yt-jackpotarmy",
    label: "Jackpot Army",
    url: "UCdSjMikohmTPDF2bggxa9CQ",
    needsFilter: false,
    fetchCount: 10,
    priority: 12,
  },
  {
    type: "youtube",
    id: "yt-dkdktv",
    label: "DKDKTV",
    url: "UCVEzR8VHu0JC5xlTr53cMwQ",
    needsFilter: true,
    fetchCount: 10,
    priority: 13,
  },

  // TikTok compilation YouTube channels
  // Enabled: false -- no verified active BTS TikTok compilation channel found.
  // Enable and update channel ID when a suitable channel is identified.
  {
    type: "youtube",
    id: "yt-bts-tiktok-compilations",
    label: "BTS TikTok Compilations",
    url: "PENDING_CHANNEL_ID",
    needsFilter: true,
    fetchCount: 10,
    priority: 14,
    enabled: false,
  },

  // Additional Reddit sources (member subs)
  {
    type: "reddit",
    id: "reddit-btsarmy",
    label: "r/BTSARMY",
    url: "BTSARMY",
    needsFilter: false,
    fetchCount: 15,
    priority: 30,
  },
  {
    type: "reddit",
    id: "reddit-korean-hiphop",
    label: "r/Korean_Hip_Hop",
    url: "Korean_Hip_Hop",
    needsFilter: true,
    fetchCount: 15,
    priority: 31,
  },
  {
    type: "reddit",
    id: "reddit-namjoon",
    label: "r/Namjoon",
    url: "Namjoon",
    needsFilter: false,
    fetchCount: 10,
    priority: 32,
  },
  {
    type: "reddit",
    id: "reddit-jinbts",
    label: "r/jinbts",
    url: "jinbts",
    needsFilter: false,
    fetchCount: 10,
    priority: 33,
  },
  {
    type: "reddit",
    id: "reddit-suga",
    label: "r/Suga",
    url: "Suga",
    needsFilter: false,
    fetchCount: 10,
    priority: 34,
  },
  {
    type: "reddit",
    id: "reddit-jhope",
    label: "r/jhope",
    url: "jhope",
    needsFilter: false,
    fetchCount: 10,
    priority: 35,
  },
  {
    type: "reddit",
    id: "reddit-jimin",
    label: "r/jimin",
    url: "jimin",
    needsFilter: false,
    fetchCount: 10,
    priority: 36,
  },
  {
    type: "reddit",
    id: "reddit-taehyung",
    label: "r/taehyung",
    url: "taehyung",
    needsFilter: false,
    fetchCount: 10,
    priority: 37,
  },
  {
    type: "reddit",
    id: "reddit-jungkook",
    label: "r/jungkook",
    url: "jungkook",
    needsFilter: false,
    fetchCount: 10,
    priority: 38,
  },

  // Google News source
  {
    type: "googlenews",
    id: "gnews-bts",
    label: "Google News: BTS",
    url: "googlenews-bts",
    needsFilter: false,
    fetchCount: 15,
    priority: 40,
  },

  // AO3 source
  {
    type: "ao3",
    id: "ao3-bts",
    label: "AO3: BTS",
    url: "ao3-bts",
    needsFilter: false,
    fetchCount: 10,
    priority: 41,
  },

  // Tumblr sources
  {
    type: "tumblr",
    id: "tumblr-bts-trans",
    label: "bts-trans",
    url: "https://bts-trans.tumblr.com/rss",
    needsFilter: false,
    fetchCount: 10,
    priority: 20,
  },
  {
    type: "tumblr",
    id: "tumblr-kimtaegis",
    label: "kimtaegis",
    url: "https://kimtaegis.tumblr.com/rss",
    needsFilter: true,
    fetchCount: 10,
    priority: 21,
  },
  {
    type: "tumblr",
    id: "tumblr-userparkjimin",
    label: "userparkjimin",
    url: "https://userparkjimin.tumblr.com/rss",
    needsFilter: true,
    fetchCount: 10,
    priority: 22,
  },
  {
    type: "tumblr",
    id: "tumblr-namjin",
    label: "namjin",
    url: "https://namjin.tumblr.com/rss",
    needsFilter: true,
    fetchCount: 10,
    priority: 23,
  },
  {
    type: "tumblr",
    id: "tumblr-jikook",
    label: "jikook",
    url: "https://jikook.tumblr.com/rss",
    needsFilter: true,
    fetchCount: 10,
    priority: 24,
  },
];
