import type { Event } from "../../types.ts";

export const events: Event[] = [
  // === ALBUM RELEASE ===
  {
    id: "album-1",
    title: "\"Arirang\" Album Release",
    date: "2026-03-20",
    venue: "All Platforms",
    city: "Worldwide",
    region: "worldwide",
    description: "BTS group album \"Arirang\" drops worldwide across all streaming platforms.",
    status: "album",
  },

  // === ASIA ===
  {
    id: "kr-1",
    title: "BTS WORLD TOUR 'ARIRANG' IN GOYANG",
    date: "2026-04-09",
    venue: "Goyang Stadium",
    city: "Goyang, South Korea",
    region: "asia",
    description: "Opening night of the Arirang World Tour.",
    status: "sold-out",
    ticketUrl: "https://world.nol.com/en/ticket/places/26000041/products/26000547",
  },
  {
    id: "kr-2",
    title: "BTS WORLD TOUR 'ARIRANG' IN GOYANG",
    date: "2026-04-11",
    venue: "Goyang Stadium",
    city: "Goyang, South Korea",
    region: "asia",
    description: "Second Goyang show.",
    status: "sold-out",
    ticketUrl: "https://world.nol.com/en/ticket/places/26000041/products/26000547",
  },
  {
    id: "kr-3",
    title: "BTS WORLD TOUR 'ARIRANG' IN GOYANG",
    date: "2026-04-12",
    venue: "Goyang Stadium",
    city: "Goyang, South Korea",
    region: "asia",
    description: "Third and final Goyang show.",
    status: "sold-out",
    ticketUrl: "https://world.nol.com/en/ticket/places/26000041/products/26000547",
  },
  {
    id: "jp-1",
    title: "BTS WORLD TOUR 'ARIRANG' IN TOKYO",
    date: "2026-04-17",
    venue: "Tokyo Dome",
    city: "Tokyo, Japan",
    region: "asia",
    description: "First Tokyo Dome show.",
    status: "sold-out",
  },
  {
    id: "jp-2",
    title: "BTS WORLD TOUR 'ARIRANG' IN TOKYO",
    date: "2026-04-18",
    venue: "Tokyo Dome",
    city: "Tokyo, Japan",
    region: "asia",
    description: "Second Tokyo Dome show.",
    status: "sold-out",
  },

  // === NORTH AMERICA ===
  {
    id: "na-1",
    title: "BTS WORLD TOUR 'ARIRANG' IN TAMPA",
    date: "2026-04-25",
    venue: "Raymond James Stadium",
    city: "Tampa, FL",
    region: "north-america",
    description: "North American tour opener.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-tampa-tampa-florida-04-25-2026/event/0D006429DD8089EB",
  },
  {
    id: "na-2",
    title: "BTS WORLD TOUR 'ARIRANG' IN TAMPA",
    date: "2026-04-26",
    venue: "Raymond James Stadium",
    city: "Tampa, FL",
    region: "north-america",
    description: "Second Tampa show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-tampa-tampa-florida-04-26-2026/event/0D006429DDDA8A21",
  },
  {
    id: "na-3",
    title: "BTS WORLD TOUR 'ARIRANG' IN TAMPA",
    date: "2026-04-28",
    venue: "Raymond James Stadium",
    city: "Tampa, FL",
    region: "north-america",
    description: "Third Tampa show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-tampa-tampa-florida-04-28-2026/event/0D00642CA71B5453",
  },
  {
    id: "na-4",
    title: "BTS WORLD TOUR 'ARIRANG' IN EL PASO",
    date: "2026-05-02",
    venue: "Sun Bowl Stadium",
    city: "El Paso, TX",
    region: "north-america",
    description: "First El Paso show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-el-el-paso-texas-05-02-2026/event/0C006429DBA5721D",
  },
  {
    id: "na-5",
    title: "BTS WORLD TOUR 'ARIRANG' IN EL PASO",
    date: "2026-05-03",
    venue: "Sun Bowl Stadium",
    city: "El Paso, TX",
    region: "north-america",
    description: "Second El Paso show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-el-el-paso-texas-05-03-2026/event/0C006429DBAC7221",
  },
  {
    id: "na-6",
    title: "BTS WORLD TOUR 'ARIRANG' IN MEXICO CITY",
    date: "2026-05-07",
    venue: "Estadio GNP Seguros",
    city: "Mexico City, Mexico",
    region: "north-america",
    description: "First Mexico City show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com.mx/bts-world-tour-arirang-in-mexico-city-ciudad-de-mexico-07-05-2026/event/1400642AA1B78268",
  },
  {
    id: "na-7",
    title: "BTS WORLD TOUR 'ARIRANG' IN MEXICO CITY",
    date: "2026-05-09",
    venue: "Estadio GNP Seguros",
    city: "Mexico City, Mexico",
    region: "north-america",
    description: "Second Mexico City show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com.mx/bts-world-tour-arirang-in-mexico-city-ciudad-de-mexico-09-05-2026/event/1400642AA32C84D5",
  },
  {
    id: "na-8",
    title: "BTS WORLD TOUR 'ARIRANG' IN MEXICO CITY",
    date: "2026-05-10",
    venue: "Estadio GNP Seguros",
    city: "Mexico City, Mexico",
    region: "north-america",
    description: "Third Mexico City show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com.mx/bts-world-tour-arirang-in-mexico-city-ciudad-de-mexico-10-05-2026/event/1400642AA32D84D7",
  },
  {
    id: "na-9",
    title: "BTS WORLD TOUR 'ARIRANG' IN STANFORD",
    date: "2026-05-16",
    venue: "Stanford Stadium",
    city: "Stanford, CA",
    region: "north-america",
    description: "First Stanford show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-stanford-stanford-california-05-16-2026/event/1C006429C95EA2B8",
  },
  {
    id: "na-10",
    title: "BTS WORLD TOUR 'ARIRANG' IN STANFORD",
    date: "2026-05-17",
    venue: "Stanford Stadium",
    city: "Stanford, CA",
    region: "north-america",
    description: "Second Stanford show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-stanford-stanford-california-05-17-2026/event/1C006429C9DDA300",
  },
  {
    id: "na-11",
    title: "BTS WORLD TOUR 'ARIRANG' IN STANFORD",
    date: "2026-05-19",
    venue: "Stanford Stadium",
    city: "Stanford, CA",
    region: "north-america",
    description: "Third Stanford show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-stanford-stanford-california-05-19-2026/event/1C006435858268EC",
  },
  {
    id: "na-12",
    title: "BTS WORLD TOUR 'ARIRANG' IN LAS VEGAS",
    date: "2026-05-23",
    venue: "Allegiant Stadium",
    city: "Las Vegas, NV",
    region: "north-america",
    description: "First Las Vegas show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-las-vegas-nevada-05-23-2026/event/17006429D233149A",
  },
  {
    id: "na-13",
    title: "BTS WORLD TOUR 'ARIRANG' IN LAS VEGAS",
    date: "2026-05-24",
    venue: "Allegiant Stadium",
    city: "Las Vegas, NV",
    region: "north-america",
    description: "Second Las Vegas show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-las-las-vegas-nevada-05-24-2026/event/17006429E3354A8C",
  },
  {
    id: "na-14",
    title: "BTS WORLD TOUR 'ARIRANG' IN LAS VEGAS",
    date: "2026-05-27",
    venue: "Allegiant Stadium",
    city: "Las Vegas, NV",
    region: "north-america",
    description: "Third Las Vegas show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-las-vegas-nevada-05-27-2026/event/17006429E3454A9E",
  },
  {
    id: "na-15",
    title: "BTS WORLD TOUR 'ARIRANG' IN LAS VEGAS",
    date: "2026-05-28",
    venue: "Allegiant Stadium",
    city: "Las Vegas, NV",
    region: "north-america",
    description: "Fourth Las Vegas show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-las-las-vegas-nevada-05-28-2026/event/17006429E3514AB0",
  },
  {
    id: "na-16",
    title: "BTS WORLD TOUR 'ARIRANG' IN EAST RUTHERFORD",
    date: "2026-08-01",
    venue: "MetLife Stadium",
    city: "East Rutherford, NJ",
    region: "north-america",
    description: "First MetLife Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-east-east-rutherford-new-jersey-08-01-2026/event/00006429EB39BB6F",
  },
  {
    id: "na-17",
    title: "BTS WORLD TOUR 'ARIRANG' IN EAST RUTHERFORD",
    date: "2026-08-02",
    venue: "MetLife Stadium",
    city: "East Rutherford, NJ",
    region: "north-america",
    description: "Second MetLife Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-east-east-rutherford-new-jersey-08-02-2026/event/00006429ED30BCEB",
  },
  {
    id: "na-18",
    title: "BTS WORLD TOUR 'ARIRANG' IN FOXBOROUGH",
    date: "2026-08-05",
    venue: "Gillette Stadium",
    city: "Foxborough, MA",
    region: "north-america",
    description: "First Gillette Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-foxborough-foxborough-massachusetts-08-05-2026/event/0100642CBD7AB56B",
  },
  {
    id: "na-19",
    title: "BTS WORLD TOUR 'ARIRANG' IN FOXBOROUGH",
    date: "2026-08-06",
    venue: "Gillette Stadium",
    city: "Foxborough, MA",
    region: "north-america",
    description: "Second Gillette Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-foxborough-foxborough-massachusetts-08-06-2026/event/0100642CC24EBB04",
  },
  {
    id: "na-20",
    title: "BTS WORLD TOUR 'ARIRANG' IN BALTIMORE",
    date: "2026-08-10",
    venue: "M&T Bank Stadium",
    city: "Baltimore, MD",
    region: "north-america",
    description: "First Baltimore show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-tickets/artist/2110227",
  },
  {
    id: "na-21",
    title: "BTS WORLD TOUR 'ARIRANG' IN BALTIMORE",
    date: "2026-08-11",
    venue: "M&T Bank Stadium",
    city: "Baltimore, MD",
    region: "north-america",
    description: "Second Baltimore show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-tickets/artist/2110227",
  },
  {
    id: "na-22",
    title: "BTS WORLD TOUR 'ARIRANG' IN ARLINGTON",
    date: "2026-08-15",
    venue: "AT&T Stadium",
    city: "Arlington, TX",
    region: "north-america",
    description: "First AT&T Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-tickets/artist/2110227",
  },
  {
    id: "na-23",
    title: "BTS WORLD TOUR 'ARIRANG' IN ARLINGTON",
    date: "2026-08-16",
    venue: "AT&T Stadium",
    city: "Arlington, TX",
    region: "north-america",
    description: "Second AT&T Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-tickets/artist/2110227",
  },
  {
    id: "na-24",
    title: "BTS WORLD TOUR 'ARIRANG' IN TORONTO",
    date: "2026-08-22",
    venue: "Rogers Stadium",
    city: "Toronto, ON",
    region: "north-america",
    description: "First Toronto show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.ca/bts-world-tour-arirang-in-toronto-toronto-ontario-08-22-2026/event/1000642B2CB3BB4D",
  },
  {
    id: "na-25",
    title: "BTS WORLD TOUR 'ARIRANG' IN TORONTO",
    date: "2026-08-23",
    venue: "Rogers Stadium",
    city: "Toronto, ON",
    region: "north-america",
    description: "Second Toronto show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.ca/bts-world-tour-arirang-in-toronto-toronto-ontario-08-23-2026/event/1000642B2D4EBBDE",
  },
  {
    id: "na-26",
    title: "BTS WORLD TOUR 'ARIRANG' IN CHICAGO",
    date: "2026-08-27",
    venue: "Soldier Field",
    city: "Chicago, IL",
    region: "north-america",
    description: "First Soldier Field show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-chicago-chicago-illinois-08-27-2026/event/0400642ACBBD5D44",
  },
  {
    id: "na-27",
    title: "BTS WORLD TOUR 'ARIRANG' IN CHICAGO",
    date: "2026-08-28",
    venue: "Soldier Field",
    city: "Chicago, IL",
    region: "north-america",
    description: "Second Soldier Field show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-chicago-chicago-illinois-08-28-2026/event/0400642ACC7E5D9B",
  },
  {
    id: "na-28",
    title: "BTS WORLD TOUR 'ARIRANG' IN LOS ANGELES",
    date: "2026-09-01",
    venue: "SoFi Stadium",
    city: "Los Angeles, CA",
    region: "north-america",
    description: "First SoFi Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-los-inglewood-california-09-01-2026/event/0A006429AB3C5EF1",
  },
  {
    id: "na-29",
    title: "BTS WORLD TOUR 'ARIRANG' IN LOS ANGELES",
    date: "2026-09-02",
    venue: "SoFi Stadium",
    city: "Los Angeles, CA",
    region: "north-america",
    description: "Second SoFi Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-los-inglewood-california-09-02-2026/event/0A006429B1B363A4",
  },
  {
    id: "na-30",
    title: "BTS WORLD TOUR 'ARIRANG' IN LOS ANGELES",
    date: "2026-09-05",
    venue: "SoFi Stadium",
    city: "Los Angeles, CA",
    region: "north-america",
    description: "Third SoFi Stadium show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-los-inglewood-california-09-05-2026/event/0A006429B2CB6418",
  },
  {
    id: "na-31",
    title: "BTS WORLD TOUR 'ARIRANG' IN LOS ANGELES",
    date: "2026-09-06",
    venue: "SoFi Stadium",
    city: "Los Angeles, CA",
    region: "north-america",
    description: "Fourth and final SoFi Stadium show -- NA tour closer.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.com/bts-world-tour-arirang-in-los-inglewood-california-09-06-2026/event/0A006429B353645F",
  },

  // === EUROPE ===
  {
    id: "eu-1",
    title: "BTS WORLD TOUR 'ARIRANG' IN MADRID",
    date: "2026-06-26",
    venue: "Riyadh Air Metropolitano",
    city: "Madrid, Spain",
    region: "europe",
    description: "European tour opener in Madrid.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.es/artist/bts-tickets/958687",
  },
  {
    id: "eu-2",
    title: "BTS WORLD TOUR 'ARIRANG' IN MADRID",
    date: "2026-06-27",
    venue: "Riyadh Air Metropolitano",
    city: "Madrid, Spain",
    region: "europe",
    description: "Second Madrid show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.es/artist/bts-tickets/958687",
  },
  {
    id: "eu-3",
    title: "BTS WORLD TOUR 'ARIRANG' IN BRUSSELS",
    date: "2026-07-01",
    venue: "King Baudouin Stadium",
    city: "Brussels, Belgium",
    region: "europe",
    description: "First Brussels show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.be/event/bts-world-tour-in-brussels-tickets/1734588080",
  },
  {
    id: "eu-4",
    title: "BTS WORLD TOUR 'ARIRANG' IN BRUSSELS",
    date: "2026-07-02",
    venue: "King Baudouin Stadium",
    city: "Brussels, Belgium",
    region: "europe",
    description: "Second Brussels show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.be/event/bts-world-tour-in-brussels-tickets/1734588080",
  },
  {
    id: "eu-5",
    title: "BTS WORLD TOUR 'ARIRANG' IN LONDON",
    date: "2026-07-06",
    venue: "Tottenham Hotspur Stadium",
    city: "London, UK",
    region: "europe",
    description: "First London show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.co.uk/bts-world-tour-arirang-in-london-london-06-07-2026/event/35006434E82D5E38",
  },
  {
    id: "eu-6",
    title: "BTS WORLD TOUR 'ARIRANG' IN LONDON",
    date: "2026-07-07",
    venue: "Tottenham Hotspur Stadium",
    city: "London, UK",
    region: "europe",
    description: "Second London show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.co.uk/bts-world-tour-arirang-in-london-london-07-07-2026/event/3500642CAF9145A0",
  },
  {
    id: "eu-7",
    title: "BTS WORLD TOUR 'ARIRANG' IN MUNICH",
    date: "2026-07-11",
    venue: "Allianz Arena",
    city: "Munich, Germany",
    region: "europe",
    description: "First Munich show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.de/event/bts-world-tour-arirang-in-munich-tickets/463609754?language=en-us",
  },
  {
    id: "eu-8",
    title: "BTS WORLD TOUR 'ARIRANG' IN MUNICH",
    date: "2026-07-12",
    venue: "Allianz Arena",
    city: "Munich, Germany",
    region: "europe",
    description: "Second Munich show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.de/event/bts-world-tour-arirang-in-munich-tickets/463609754?language=en-us",
  },
  {
    id: "eu-9",
    title: "BTS WORLD TOUR 'ARIRANG' IN PARIS",
    date: "2026-07-17",
    venue: "Stade De France",
    city: "Paris, France",
    region: "europe",
    description: "First Paris show.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.fr/en/manifestation/bts-world-tour-arirang-in-paris-ticket/idmanif/647177",
  },
  {
    id: "eu-10",
    title: "BTS WORLD TOUR 'ARIRANG' IN PARIS",
    date: "2026-07-18",
    venue: "Stade De France",
    city: "Paris, France",
    region: "europe",
    description: "Second Paris show -- European tour closer.",
    status: "on-sale",
    ticketUrl: "https://www.ticketmaster.fr/en/manifestation/bts-world-tour-arirang-in-paris-ticket/idmanif/647177",
  },
];
