import type { MemberConfig } from "../../types.ts";

export const members: MemberConfig[] = [
  {
    id: "rm",
    stageName: "RM",
    realName: "Kim Namjoon",
    aliases: ["rm", "namjoon", "kim namjoon", "mono", "indigo", "nam joon", "rapmon", "rap monster"],
    emoji: "\u{1F428}",
    color: "#1a1a2e",
    birthday: "September 12, 1994",
    role: "Leader, Main Rapper",
    position: "Leader",
    image: "/members/rm.jpg",
    gallery: ["/members/rm-2.jpg", "/members/rm-3.jpg", "/members/rm-4.jpg", "/members/rm-5.jpg"],
    bio: "RM is the leader and main rapper of BTS. Known for his high IQ of 148 and fluent English, he is the primary songwriter and producer of the group. He learned English by watching Friends and has written and produced hundreds of songs.",
    funFacts: [
      "IQ of 148",
      "Learned English by watching Friends",
      "Loves visiting art museums",
      "Has a collection of figurines",
      "Scored in the top 1% on national exams",
    ],
    soloProjects: ["mono. (mixtape)", "Indigo (solo album)", "Right Place, Wrong Person"],
    socialMedia: [
      { platform: "Instagram", handle: "@rkive" },
      { platform: "Spotify", handle: "RM", url: "https://open.spotify.com/artist/4rghtUEklOGTB3MgHIWnOF" },
    ],
  },
  {
    id: "jin",
    stageName: "Jin",
    realName: "Kim Seokjin",
    aliases: ["jin", "seokjin", "kim seokjin", "worldwide handsome", "astronaut", "seok jin", "wwh"],
    emoji: "\u{1F439}",
    color: "#16213e",
    birthday: "December 4, 1992",
    role: "Vocalist, Visual",
    position: "Sub Vocalist, Visual",
    image: "/members/jin.jpg",
    gallery: ["/members/jin-2.jpg", "/members/jin-3.jpg", "/members/jin-4.jpg", "/members/jin-5.jpg"],
    bio: "Jin is the eldest member of BTS, known as the group's visual and for his incredible vocal range. His warm personality and dad jokes have earned him the nickname 'Worldwide Handsome.' He studied acting at Konkuk University.",
    funFacts: [
      "Known as 'Worldwide Handsome'",
      "Famous for his dad jokes",
      "Excellent cook - loves making recipes",
      "Studied acting at Konkuk University",
      "Has pet sugar gliders named Odeng and Eomuk",
    ],
    soloProjects: ["The Astronaut (single)", "Running Wild"],
    socialMedia: [
      { platform: "Instagram", handle: "@jin" },
      { platform: "Spotify", handle: "Jin", url: "https://open.spotify.com/artist/5vV3bFXnspGKeFokaIXJvY" },
    ],
  },
  {
    id: "suga",
    stageName: "SUGA",
    realName: "Min Yoongi",
    aliases: ["suga", "yoongi", "min yoongi", "agust d", "d-day", "d-2", "agustd", "min suga"],
    emoji: "\u{1F431}",
    color: "#0f3460",
    birthday: "March 9, 1993",
    role: "Lead Rapper, Producer",
    position: "Lead Rapper",
    image: "/members/suga.jpg",
    gallery: ["/members/suga-2.jpg", "/members/suga-3.jpg", "/members/suga-4.jpg", "/members/suga-5.jpg"],
    bio: "SUGA is a rapper, songwriter, and record producer. Also known by his solo alias Agust D, he is one of the most prolific producers in K-pop. Before BTS, he worked as an underground rapper in Daegu.",
    funFacts: [
      "Also known as Agust D",
      "Was an underground rapper before BTS",
      "Produces music for other artists too",
      "Loves basketball",
      "Known for his savage wit and dry humor",
    ],
    soloProjects: ["Agust D (mixtape)", "D-2 (mixtape)", "D-DAY (solo album)"],
    socialMedia: [
      { platform: "Instagram", handle: "@agustd" },
      { platform: "Spotify", handle: "Agust D", url: "https://open.spotify.com/artist/1oSPZhvZMIrWW5I3cAvSCz" },
    ],
  },
  {
    id: "jhope",
    stageName: "j-hope",
    realName: "Jung Hoseok",
    aliases: ["j-hope", "jhope", "hoseok", "jung hoseok", "hope world", "jack in the box", "hobi", "j hope"],
    emoji: "\u{1F43F}\uFE0F",
    color: "#533483",
    birthday: "February 18, 1994",
    role: "Main Dancer, Sub Rapper",
    position: "Main Dancer",
    image: "/members/jhope.jpg",
    gallery: ["/members/jhope-2.jpg", "/members/jhope-3.jpg", "/members/jhope-4.jpg", "/members/jhope-5.jpg"],
    bio: "j-hope is the main dancer and sub rapper of BTS. Known as the group's sunshine and mood maker, he was a street dancer before joining BTS. His energy and positive attitude are infectious both on and off stage.",
    funFacts: [
      "Known as BTS's sunshine",
      "Won a national dance competition as a student",
      "His stage name represents hope",
      "Amazing street dancer before joining BTS",
      "Known for his iconic 'Hobi scream'",
    ],
    soloProjects: ["Hope World (mixtape)", "Jack In The Box (solo album)", "HOPE ON THE STREET"],
    socialMedia: [
      { platform: "Instagram", handle: "@uarmyhope" },
      { platform: "Spotify", handle: "j-hope", url: "https://open.spotify.com/artist/0b1sIQumIAsNbqAoAClMHY" },
    ],
  },
  {
    id: "jimin",
    stageName: "Jimin",
    realName: "Park Jimin",
    aliases: ["jimin", "park jimin", "face album", "muse album", "chimchim", "chim chim"],
    emoji: "\u{1F425}",
    color: "#5b2c6f",
    birthday: "October 13, 1995",
    role: "Main Dancer, Lead Vocalist",
    position: "Main Dancer, Lead Vocalist",
    image: "/members/jimin.jpg",
    gallery: ["/members/jimin-2.jpg", "/members/jimin-3.jpg", "/members/jimin-4.jpg", "/members/jimin-5.jpg"],
    bio: "Jimin is a main dancer and lead vocalist known for his contemporary dance background, powerful stage presence, and emotive vocals. He studied contemporary dance at Busan High School of Arts before transferring to Korea Arts High School.",
    funFacts: [
      "Trained in contemporary dance",
      "Known for his incredible flexibility",
      "Has the most #1 hits as a K-pop soloist",
      "Famous for his eye smile",
      "Very caring and affectionate with members",
    ],
    soloProjects: ["FACE (solo album)", "MUSE (solo album)"],
    socialMedia: [
      { platform: "Instagram", handle: "@j.m" },
      { platform: "Spotify", handle: "Jimin", url: "https://open.spotify.com/artist/1oSPZhvZMIrWW5I3cAvSCz" },
    ],
  },
  {
    id: "v",
    stageName: "V",
    realName: "Kim Taehyung",
    aliases: ["taehyung", "kim taehyung", "layover", "winter ahead", "tae", "taetae", "tae tae"],
    emoji: "\u{1F42F}",
    color: "#4a235a",
    birthday: "December 30, 1995",
    role: "Vocalist, Visual",
    position: "Sub Vocalist, Visual",
    image: "/members/v.jpg",
    gallery: ["/members/v-2.jpg", "/members/v-3.jpg", "/members/v-4.jpg", "/members/v-5.jpg"],
    bio: "V is known for his deep, soulful baritone voice, acting talent, and unique artistic sensibility. He was a hidden member, revealed only at BTS's debut. His love for art, photography, and vintage aesthetics makes him a true creative soul.",
    funFacts: [
      "Has a unique deep baritone voice",
      "Was a 'hidden member' before debut",
      "Loves photography and art",
      "Acted in the K-drama Hwarang",
      "Known for his boxy smile",
    ],
    soloProjects: ["Layover (solo album)", "Winter Ahead (single)"],
    socialMedia: [
      { platform: "Instagram", handle: "@thv" },
      { platform: "Spotify", handle: "V", url: "https://open.spotify.com/artist/2cFrymmkijnjDg9SS92EPM" },
    ],
  },
  {
    id: "jungkook",
    stageName: "Jungkook",
    realName: "Jeon Jungkook",
    aliases: ["jungkook", "jeon jungkook", "golden", "standing next to you", "jk", "kookie", "jung kook"],
    emoji: "\u{1F430}",
    color: "#1b2631",
    birthday: "September 1, 1997",
    role: "Main Vocalist, Lead Dancer, Sub Rapper",
    position: "Main Vocalist, Center",
    image: "/members/jungkook.jpg",
    gallery: ["/members/jungkook-2.jpg", "/members/jungkook-3.jpg", "/members/jungkook-4.jpg", "/members/jungkook-5.jpg"],
    bio: "Jungkook is the youngest member (maknae) of BTS and is often called the 'Golden Maknae' for his exceptional talent in singing, dancing, and virtually everything he tries. He joined BTS at just 15 years old.",
    funFacts: [
      "Known as the 'Golden Maknae'",
      "Joined BTS at age 15",
      "Good at almost every sport he tries",
      "Loves drawing and is very artistic",
      "His cover songs regularly break streaming records",
    ],
    soloProjects: ["GOLDEN (solo album)", "Standing Next to You (single)"],
    socialMedia: [
      { platform: "Instagram", handle: "@jungkook" },
      { platform: "Spotify", handle: "Jung Kook", url: "https://open.spotify.com/artist/6HaGTQPmv1OTuIE5MgJiBE" },
    ],
  },
];
